# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Install dependencies
      run: bundle install
    - name: Set up cardano-wallet & cardano-node on Shelley testnet
      run: |
        wget https://raw.githubusercontent.com/piotr-iohk/cardano-wallet-rb/master/docker-compose.yml -O docker-compose-test.yml
        wget $CONFIG_URL/testnet-config.json
        wget $CONFIG_URL/testnet-byron-genesis.json
        wget $CONFIG_URL/testnet-shelley-genesis.json
        wget $CONFIG_URL/testnet-alonzo-genesis.json
        wget $CONFIG_URL/testnet-topology.json
        NODE_CONFIG_PATH=`pwd` docker-compose -f docker-compose-test.yml up --detach
    - name: Run tests
      run: rspec tests
    env:
      CONFIG_URL: https://hydra.iohk.io/job/Cardano/cardano-node/cardano-deployment/latest-finished/download/1
      NETWORK: testnet
      WALLET: dev-master
      NODE: alonzo-purple-1.0.1
      TOKEN_METADATA: https://metadata.cardano-testnet.iohkdev.io/
