name: Docker

on:
  push:
    tags:
    - '*'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Get the tag
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      id: get_tag
      run: |
        echo $GITHUB_REF | cut -d / -f 3
        echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Build and push on release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      id: docker_build_release
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: piotrstachyra/icarus:latest,piotrstachyra/icarus:${{ steps.get_tag.outputs.VERSION }}

    - name: Build and push on master
      if: ${{ startsWith(github.ref, 'refs/heads/master')}}
      id: docker_build_master
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: piotrstachyra/icarus:master
